### PR TITLE
Introducing Microsoft.Build.Sql

### PR DESCRIPTION
**Pull request by zijchen**
Introducing Microsoft.Build.Sql as a .NET SDK to build database projects. This is the initial commit of the SDK and support for more functionality will be added incrementally. Feel free to give this a try and open issues for any bugs/feature requests.

Microsoft.Build.Sql.csproj copies DLLs from dependent packages into a \Tools\ folder. This folder, along with Sdk.props and Sdk.targets, make up the rest of the SDK.

To build a sqlproj with this SDK, simply add a line after the `<Project>` tag: `<Sdk Name="Microsoft.Build.Sql" Version="1.0.0" />` and remove any extra unnecessary items.
To build, run `dotnet build /p:NetCoreBuild=true`

See [\src\Microsoft.Build.Sql\README](https://github.com/microsoft/DacFx/blob/019114803cc785b970e6b4eee56e4b3c2774ed53/src/Microsoft.Build.Sql/README.md) for more details, including how to configure a local Nuget source and a workaround for .NET 6 preview.

Lastly, I would like to thank @jmezach for the work he has done with MSBuild.Sdk.SqlProj as an inspiration for this project. It highlighted some areas for improvement with the existing Build process for database projects that we hope to tackle with this SDK.

### CODE REVIEW

**Comment by zijchen** [comment]
> Why not publish a preview package to a public 3rd party feed, or even Azure DevOps feed?

That's a good suggestion. @dzsquared do you know if that's something we can do per CELA/compliance?

**Comment by ErikEJ** [comment]
I made an attempt, but failed:

```
Build started...
------ Build started: Project: Stepup.Database, Configuration: Debug Any CPU ------
		C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE;DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /debug+ /debug:full /optimize- /out:obj\Debug\Stepup.Database.dll /subsystemversion:6.00 /target:library /warnaserror- /utf8output /langversion:7.3 "C:\Users\eejj\AppData\Local\Temp\.NETFramework,Version=v4.5.SqlClrAttributes.cs"
C:\Users\eejj\.nuget\packages\microsoft.build.sql\1.0.0\tools\netstandard2.0\Microsoft.Data.Tools.Schema.SqlTasks.targets(504,5): Error:  MSB4062: The "SqlModelResolutionTask" task could not be loaded from the assembly C:\Users\eejj\.nuget\packages\microsoft.build.sql\1.0.0\Sdk\..\tools\netstandard2.0\Microsoft.Data.Tools.Schema.Tasks.Sql.dll. Could not load file or assembly 'Microsoft.Data.Tools.Schema.Tasks.Sql, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building project "Stepup.Database.sqlproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

```

**Comment by ErikEJ** [comment]
Attempted, but failed:

```
Build started...
------ Build started: Project: Stepup.Database, Configuration: Debug Any CPU ------
		C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702,2008 /fullpaths /nostdlib+ /errorreport:prompt /warn:4 /define:DEBUG;TRACE;DEBUG;TRACE /errorendlocation /preferreduilang:en-US /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /debug+ /debug:full /optimize- /out:obj\Debug\Stepup.Database.dll /subsystemversion:6.00 /target:library /warnaserror- /utf8output /langversion:7.3 "C:\Users\xxxx\AppData\Local\Temp\.NETFramework,Version=v4.5.SqlClrAttributes.cs"
C:\Users\xxxx\.nuget\packages\microsoft.build.sql\1.0.0\tools\netstandard2.0\Microsoft.Data.Tools.Schema.SqlTasks.targets(504,5): Error:  MSB4062: The "SqlModelResolutionTask" task could not be loaded from the assembly C:\Users\xxxx\.nuget\packages\microsoft.build.sql\1.0.0\Sdk\..\tools\netstandard2.0\Microsoft.Data.Tools.Schema.Tasks.Sql.dll. Could not load file or assembly 'Microsoft.Data.Tools.Schema.Tasks.Sql, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.
Done building project "Stepup.Database.sqlproj" -- FAILED.

Build FAILED.
========== Build: 0 succeeded or up-to-date, 1 failed, 0 skipped ==========

```

**Review by llali — APPROVED** [review]

**Comment by Benjin** [comment]
There are a few comment threads in here about updated DacFx (MDS 3+, .NET Core dependency bump, SqlTasks inclusions).  Are you planning to check this in with the current dependencies and update as those become available, or is this PR more of a rolling preview and it won't get merged until 160 + SqlTasks is released and we can target that instead?

**Comment by zijchen** [comment]
> There are a few comment threads in here about updated DacFx (MDS 3+, .NET Core dependency bump, SqlTasks inclusions). Are you planning to check this in with the current dependencies and update as those become available, or is this PR more of a rolling preview and it won't get merged until 160 + SqlTasks is released and we can target that instead?

I plan on doing the dependency bumps in a later PR. The 160 preview nuget was released before the SqlTasks were moved back to DacFx so I can't use that right now. I'll wait for the next preview release before bumping it.

I'll create tasks for all the open feedback from this thread before I close this PR.

**Comment by agoodwin** [comment]
I'm over a year late, but wow, thank you for this. I didn't think this was something being worked on, but this is going to make our development so much nicer.

**Pull request merged**
